CREATE TABLE `sites` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	`sitename` VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`uri` VARCHAR(128) NULL DEFAULT NULL COMMENT 'url' COLLATE 'utf8mb4_general_ci',
	`create_time` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
	`visit_num` INT(10) UNSIGNED NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `sitename` (`sitename`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=14
;

CREATE TABLE `visit_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  `time` INT UNSIGNED NOT NULL COMMENT '访问时间',
  `cost_time` INT NOT NULL COMMENT '接口响应时间',
  `path` VARCHAR(128) NOT NULL COMMENT 'api',
  `ip` VARCHAR(32) COMMENT '客户端IP',
  `method` VARCHAR(10) COMMENT '请求方法',
  PRIMARY KEY (`id`) USING BTREE
)COMMENT '访问记录表' CHARSET=utf8mb4 ENGINE=InnoDB;
